#if defined treason_hudtext_included
  #endinput
#endif
#define treason_hudtext_included

#define ABOVECHATTEXT_X 0.008
#define ABOVECHATTEXT_Y 0.49
#define ABOVECENTERTEXT_X -1.0
#define ABOVECENTERTEXT_Y 0.19
#define ROLETEXT_X 0.093
#define ROLETEXT_Y 0.798
#define JESTERTEXT_X 0.1185
#define JESTERTEXT_Y 0.798
#define RIGHTOFCLUESTEXT_X 0.69
#define RIGHTOFCLUESTEXT_Y 0.02
#define AUTO_CHANNEL -1